set.seed(4060)
library(glmnet)
dat = read.csv(file='blood_pressure.csv')
x = dat$BMI
y = dat$Systolic
glmo = glm(Systolic~BMI, data=dat)
# (a)
sqrt(mean(residuals(glmo)^2))
kde = density(scale(glmo$residuals))
# (b)
kde$bw
f.ref = dnorm(kde$x,0,1)
# (c)
sqrt(mean((kde$y-f.ref)^2))
f.t = dt(kde$x,2)
# (d)
sqrt(mean((kde$y-f.t)^2))
library(splines) # contains function bs()
KN = quantile(dat$BMI, c(0.15, 0.60, 0.70, 0.80))
BM = bs(dat$BMI, knots=KN)
B.spline = lm(y~BM)
# (f)
sqrt(mean(residuals(B.spline)^2))
# (g)
plot(dat$BMI,dat$Systolic,pch=20)
lines(dat$BMI,fitted(glmo))
os = order(dat$BMI)
lines(dat$BMI[os],fitted(B.spline)[os],col=3,lwd=2)